# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Twnsnd Co
description: "my portfolio, but running with gulp. so way faster."
tagline: I'm just happy to be here. Co-founder of Meeet Co. Designer of The News App. Curator of New Old Stock. Soon to be apprentice at Thoughtbot.
url: ''
dev_url: 'http://localhost:3000'

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: "Cole Townsend"
  email: "cole@coletownsend.com"
  bio: "I'm just happy to be here. Co-founder of Meeet Co. Designer of The News App. Curator of New Old Stock. Soon to be apprentice at Thoughtbot."
  twitter: "twnsndco"

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

exclude: ['README.md', 'gulpfile.js', '*.codekit', 'Gemfile.lock', 'Gemfile', '.gitignore', 'templates', '*.sublime-workspace', '*.sublime-project', '_config.yml', '*.scssc', 'bower_components']

# Permalink structure and pagination options
paginate: 1000

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

permalink: /:categories/:title

###############
# Asset links #
###############
# images
image:
  inline: /assets/images/inline/
  assets: /assets/images/assets/
  post: /assets/images/posts/

# scripts
script: /assets/javascript/



###############
# Nav links   #
###############
links:
- title: Home
  url: /
- title: Work
  url: /work/
- title: Journal
  url: /journal/
- title: About
  url: /about/
